### ISSUE TITLE
`CapabilitiesClient.list_category` method not working

### ISSUE THREAD

**Issue by hh2110** [Synqly/python-sdk#33]
When calling the `CapabilitiesClient.list_category` method, pydantic raises an error because the category object is expected to have a `CategoryId` returned with it but when one tries the `https://api.synqly.com/v1/capabilities/category` view, the object returned does not include `CategoryId` so currently the SDK cannot return lists of categories. According to the [api-docs](https://docs.synqly.com/reference/capabilities_list_category), the `CategoryId` should be returned as well. 

UPDATE (2/9/24) -- looks like there is also another pydantic related error when calling: `permission_sets = management_client.permissionset.list()`
- looks like the permissions given to certain sets are no compliant with the corresponding pyndatic model; e.g. `AuditActions` can only be one of `"list" OR "*"` but the `"v1/permissionsets"` endpoint returns `"get"` as one of the actions so pydantic raises an error:
  ```permissions -> audit -> actions -> 1
    value is not a valid enumeration member; permitted: 'list', '*' (type=type_error.enum; enum_values=[<AuditActions.LIST: 'list'>, <AuditActions.ALL: '*'>])
  ```

**Comment by arcurtis** [comment]
Thanks for the feedback @hh2110. We have fixed these issues in the latest version of the SDK version `0.2.98`.
